package controlplane

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/SamuelMolling/godwit/internal/engine"
)

// depCase is one dependent kind bound to <tbl>.age and the fragment its refusal must name.
type depCase struct {
	tbl  string
	ddl  []string
	up   string
	want string
}

func depTable(name string) string {
	return fmt.Sprintf(`CREATE TABLE public.%s (
		id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		email text NOT NULL,
		age integer NOT NULL,
		price integer
	)`, name)
}

// changeTypeDependents is every dependent kind pg_depend reports on a column. Each one silently follows
// the physical attribute across the contract phase's two renames.
var changeTypeDependents = map[string]depCase{
	"view": {
		tbl:  "d_view",
		ddl:  []string{`CREATE VIEW public.order_stats AS SELECT id, age FROM public.d_view`},
		want: "view public.order_stats depends on public.d_view.age",
	},
	"materialized view": {
		tbl:  "d_matview",
		ddl:  []string{`CREATE MATERIALIZED VIEW public.age_mv AS SELECT id, age FROM public.d_matview`},
		want: "materialized view public.age_mv depends on",
	},
	"index": {
		tbl:  "d_index",
		ddl:  []string{`CREATE INDEX d_index_age_idx ON public.d_index (age)`},
		want: "index public.d_index_age_idx depends on",
	},
	"expression index": {
		tbl:  "d_exprindex",
		ddl:  []string{`CREATE INDEX d_exprindex_age_idx ON public.d_exprindex ((age * 2))`},
		want: "index public.d_exprindex_age_idx depends on",
	},
	"partial index": {
		tbl:  "d_partindex",
		ddl:  []string{`CREATE INDEX d_partindex_age_idx ON public.d_partindex (email) WHERE age > 2`},
		want: "index public.d_partindex_age_idx depends on",
	},
	"unique constraint": {
		tbl:  "d_unique",
		ddl:  []string{`ALTER TABLE public.d_unique ADD CONSTRAINT d_unique_age_key UNIQUE (age)`},
		want: "unique constraint d_unique_age_key on public.d_unique depends on",
	},
	"primary key": {
		ddl:  []string{`CREATE TABLE public.d_pk (age integer PRIMARY KEY, price integer)`},
		up:   "-- godwit: change-type d_pk.age bigint\n",
		want: "primary key d_pk_pkey on public.d_pk depends on",
	},
	"check constraint": {
		tbl:  "d_check",
		ddl:  []string{`ALTER TABLE public.d_check ADD CONSTRAINT d_check_age_pos CHECK (age > 0)`},
		want: "check constraint d_check_age_pos on public.d_check depends on",
	},
	"exclusion constraint": {
		tbl:  "d_excl",
		ddl:  []string{`ALTER TABLE public.d_excl ADD CONSTRAINT d_excl_age EXCLUDE USING btree (age WITH =)`},
		want: "exclusion constraint d_excl_age on public.d_excl depends on",
	},
	"trigger on the column": {
		tbl: "d_trigger",
		ddl: []string{
			`CREATE FUNCTION public.d_noop() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN new; END $$`,
			`CREATE TRIGGER d_trg AFTER UPDATE OF age ON public.d_trigger FOR EACH ROW EXECUTE FUNCTION public.d_noop()`,
		},
		want: "trigger d_trg on public.d_trigger depends on",
	},
	"generated column": {
		tbl:  "d_gen",
		ddl:  []string{`ALTER TABLE public.d_gen ADD COLUMN twice integer GENERATED ALWAYS AS (age * 2) STORED`},
		want: "generated column public.d_gen.twice depends on",
	},
	"rule": {
		tbl: "d_rule",
		ddl: []string{
			`CREATE TABLE public.d_log (a integer)`,
			`CREATE RULE d_rule AS ON INSERT TO public.d_rule DO ALSO INSERT INTO public.d_log VALUES (new.age)`,
		},
		want: "rule d_rule on public.d_rule depends on",
	},
	"publication column list": {
		tbl:  "d_pubcols",
		ddl:  []string{`CREATE PUBLICATION d_pub FOR TABLE public.d_pubcols (id, age)`},
		want: "publication d_pub depends on",
	},
	"row security policy": {
		tbl: "d_policy",
		ddl: []string{
			`ALTER TABLE public.d_policy ENABLE ROW LEVEL SECURITY`,
			`CREATE POLICY d_pol ON public.d_policy USING (age > 0)`,
		},
		want: "row security policy d_pol on public.d_policy depends on",
	},
	"statistics object": {
		tbl:  "d_stats",
		ddl:  []string{`CREATE STATISTICS public.d_st ON age, email FROM public.d_stats`},
		want: "statistics object public.d_st depends on",
	},
	"sequence owned by the column": {
		tbl:  "d_owned",
		ddl:  []string{`CREATE SEQUENCE public.d_seq OWNED BY public.d_owned.age`},
		want: "sequence public.d_seq depends on",
	},
}

func TestExpandRefusesChangeTypeDependents(t *testing.T) {
	t.Parallel()
	for kind, tc := range changeTypeDependents {
		t.Run(kind, func(t *testing.T) {
			ddl := append([]string{depTable(tc.tbl)}, tc.ddl...)
			if tc.up != "" {
				ddl = tc.ddl
			}
			conn := newScratch(t, ddl...)
			up := tc.up
			if up == "" {
				up = "-- godwit: change-type " + tc.tbl + ".age bigint\n"
			}
			_, err := expandOne(t, conn, up, revertSentinel)
			if err == nil {
				t.Fatal("the swap would rebind this dependent to age_old; the expander must refuse")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
			if !strings.Contains(err.Error(), "would silently keep reading") {
				t.Fatalf("the refusal must say why: %v", err)
			}
		})
	}
}

// TestChangeTypeSwapRebindsDependents is the hazard the refusal exists for, shown on PostgreSQL itself:
// the two renames of the contract phase move every dependent onto the retired column without an error.
func TestChangeTypeSwapRebindsDependents(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	conn := newScratch(t, depTable("swap"),
		`CREATE VIEW public.swap_v AS SELECT id, age FROM public.swap`,
		`CREATE INDEX swap_age_idx ON public.swap (age)`,
		`ALTER TABLE public.swap ADD CONSTRAINT swap_age_pos CHECK (age > 0)`,
	)
	for _, s := range []string{
		`ALTER TABLE public.swap ADD COLUMN age_new bigint`,
		`ALTER TABLE public.swap RENAME COLUMN age TO age_old`,
		`ALTER TABLE public.swap RENAME COLUMN age_new TO age`,
	} {
		if _, err := conn.Exec(ctx, s); err != nil {
			t.Fatalf("%s: %v", s, err)
		}
	}
	for probe, want := range map[string]string{
		`SELECT pg_get_viewdef('public.swap_v'::regclass)`:                                   "age_old",
		`SELECT pg_get_indexdef('public.swap_age_idx'::regclass)`:                            "age_old",
		`SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = 'swap_age_pos'`: "age_old",
		`SELECT format_type(atttypid, atttypmod) FROM pg_attribute
		   WHERE attrelid = 'public.swap'::regclass AND attname = 'age'`: "bigint",
	} {
		var got string
		if err := conn.QueryRow(ctx, probe).Scan(&got); err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(got, want) {
			t.Fatalf("%s = %q, want %q", probe, got, want)
		}
	}
}

func TestExpandChangeTypeAllowsAnUndependedColumn(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL,
		`CREATE INDEX users_email_idx ON public.users (email)`,
		`ALTER TABLE public.users ADD CONSTRAINT users_email_len CHECK (length(email) > 0)`,
	)
	if _, err := expandOne(t, conn, changeAge, revertSentinel); err != nil {
		t.Fatalf("objects on other columns must not block the swap: %v", err)
	}
}

// TestExpandChangeTypeCarriesTheDefault covers the one thing a rename loses that belongs to the column
// itself rather than to another object: godwit puts it back on the new column instead of refusing.
func TestExpandChangeTypeCarriesTheDefault(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL, `ALTER TABLE public.users ALTER COLUMN age SET DEFAULT 7`,
		`INSERT INTO public.users (email, age) VALUES ('a', 1)`)
	exp, err := expandOne(t, conn, changeAge, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "ALTER TABLE public.users ALTER COLUMN age_new SET DEFAULT 7;") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(strings.Join(exp.Notes, "\n"), "carries the default 7") {
		t.Fatalf("notes = %v", exp.Notes)
	}
	applyExpansion(t, conn, changeAge, revertSentinel, exp)
	var def string
	if err := conn.QueryRow(context.Background(), `
		SELECT pg_get_expr(ad.adbin, ad.adrelid) FROM pg_attrdef ad
		JOIN pg_attribute a ON a.attrelid = ad.adrelid AND a.attnum = ad.adnum
		WHERE ad.adrelid = 'public.users'::regclass AND a.attname = 'age'`).Scan(&def); err != nil {
		t.Fatalf("the swapped column kept no default: %v", err)
	}
	if def != "7" {
		t.Fatalf("default = %q", def)
	}
}

func TestExpandKeepOldFalseRefusesDependents(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, depTable("ko"), `CREATE VIEW public.ko_v AS SELECT id, age FROM public.ko`)
	_, err := expandOne(t, conn, "-- godwit: change-type ko.age bigint keep-old=false\n", "SELECT 1;\n")
	if err == nil || !strings.Contains(err.Error(), "view public.ko_v depends on public.ko.age") {
		t.Fatalf("err = %v", err)
	}
}

// dropColumnDependents splits by what PostgreSQL does to the object when the column goes: a normal
// dependency makes DROP COLUMN fail outright, an auto one is destroyed silently.
var dropColumnDependents = map[string]depCase{
	"view": {
		tbl:  "k_view",
		ddl:  []string{`CREATE VIEW public.k_view_v AS SELECT id, age FROM public.k_view`},
		want: "view public.k_view_v depends on public.k_view.age; PostgreSQL refuses",
	},
	"materialized view": {
		tbl:  "k_matview",
		ddl:  []string{`CREATE MATERIALIZED VIEW public.k_matview_v AS SELECT id, age FROM public.k_matview`},
		want: "materialized view public.k_matview_v depends on",
	},
	"trigger on the column": {
		tbl: "k_trigger",
		ddl: []string{
			`CREATE FUNCTION public.k_noop() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN new; END $$`,
			`CREATE TRIGGER k_trg AFTER UPDATE OF age ON public.k_trigger FOR EACH ROW EXECUTE FUNCTION public.k_noop()`,
		},
		want: "trigger k_trg on public.k_trigger depends on",
	},
	"generated column": {
		tbl:  "k_gen",
		ddl:  []string{`ALTER TABLE public.k_gen ADD COLUMN twice integer GENERATED ALWAYS AS (age * 2) STORED`},
		want: "generated column public.k_gen.twice depends on",
	},
	"rule": {
		tbl: "k_rule",
		ddl: []string{
			`CREATE TABLE public.k_log (a integer)`,
			`CREATE RULE k_rule AS ON INSERT TO public.k_rule DO ALSO INSERT INTO public.k_log VALUES (new.age)`,
		},
		want: "rule k_rule on public.k_rule depends on",
	},
	"publication column list": {
		tbl:  "k_pubcols",
		ddl:  []string{`CREATE PUBLICATION k_pub FOR TABLE public.k_pubcols (id, age)`},
		want: "publication k_pub depends on",
	},
	"row security policy": {
		tbl: "k_policy",
		ddl: []string{
			`ALTER TABLE public.k_policy ENABLE ROW LEVEL SECURITY`,
			`CREATE POLICY k_pol ON public.k_policy USING (age > 0)`,
		},
		want: "row security policy k_pol on public.k_policy depends on",
	},
	"foreign key from another table": {
		tbl: "k_fk",
		ddl: []string{
			`ALTER TABLE public.k_fk ADD CONSTRAINT k_fk_age_key UNIQUE (age)`,
			`CREATE TABLE public.k_fk_child (a integer REFERENCES public.k_fk (age))`,
		},
		want: "foreign key k_fk_child_a_fkey on public.k_fk_child depends on",
	},
	"index over other columns too": {
		tbl:  "k_multi",
		ddl:  []string{`CREATE INDEX k_multi_idx ON public.k_multi (age, price)`},
		want: "index public.k_multi_idx depends on public.k_multi.age and also covers other columns",
	},
	"check constraint over other columns too": {
		tbl:  "k_span",
		ddl:  []string{`ALTER TABLE public.k_span ADD CONSTRAINT k_span_ck CHECK (age > 0 AND price > 0)`},
		want: "check constraint k_span_ck on public.k_span depends on public.k_span.age and also covers",
	},
	"statistics object": {
		tbl:  "k_stats",
		ddl:  []string{`CREATE STATISTICS public.k_st ON age, email FROM public.k_stats`},
		want: "statistics object public.k_st depends on public.k_stats.age and also covers",
	},
}

func TestExpandRefusesDropColumnDependents(t *testing.T) {
	t.Parallel()
	for kind, tc := range dropColumnDependents {
		t.Run(kind, func(t *testing.T) {
			conn := newScratch(t, append([]string{depTable(tc.tbl)}, tc.ddl...)...)
			_, err := expandOne(t, conn, "-- godwit: drop-column "+tc.tbl+".age\n", "SELECT 1;\n")
			if err == nil {
				t.Fatal("the drop would break this dependent; the expander must refuse")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
		})
	}
}

// TestExpandDropColumnKeepsWhatBelongsToTheColumn is the other half of the line droppable draws: an object
// that exists only for this column is meant to go with it.
func TestExpandDropColumnKeepsWhatBelongsToTheColumn(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, depTable("own"),
		`CREATE INDEX own_age_idx ON public.own (age)`,
		`ALTER TABLE public.own ADD CONSTRAINT own_age_pos CHECK (age > 0)`,
		`ALTER TABLE public.own ALTER COLUMN age SET DEFAULT 3`,
		`CREATE SEQUENCE public.own_seq OWNED BY public.own.age`,
	)
	up := "-- godwit: drop-column own.age\n"
	exp, err := expandOne(t, conn, up, "SELECT 1;\n")
	if err != nil {
		t.Fatalf("an index, check, default and sequence of this column alone go with it: %v", err)
	}
	applyExpansion(t, conn, up, "SELECT 1;\n", exp)
	var n int
	if err := conn.QueryRow(context.Background(),
		`SELECT count(*) FROM pg_attribute WHERE attrelid = 'public.own'::regclass AND attname = 'age' AND NOT attisdropped`).
		Scan(&n); err != nil {
		t.Fatal(err)
	}
	if n != 0 {
		t.Fatalf("column count = %d", n)
	}
}

func TestDependentsProbeErrors(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, depTable("probe"), `CREATE VIEW public.probe_v AS SELECT id, age FROM public.probe`)
	col := columnFacts{Schema: "public", Table: "probe", Column: "age"}
	n := 0
	if _, err := col.dependents(context.Background(), flakyDB{DB: conn, n: &n, fail: 1}); err == nil ||
		!strings.Contains(err.Error(), "inspect public.probe.age dependencies") {
		t.Fatalf("query err = %v", err)
	}
	n = 0
	if _, err := col.dependents(context.Background(), flakyDB{DB: conn, n: &n, fail: 1, sub: "SELECT 1"}); err == nil ||
		!strings.Contains(err.Error(), "read public.probe.age dependencies") {
		t.Fatalf("collect err = %v", err)
	}
	d := engine.Directive{Line: 1, Text: "godwit: drop-column probe.age"}
	n = 0
	if err := col.droppable(context.Background(), flakyDB{DB: conn, n: &n, fail: 1}, d); err == nil {
		t.Fatalf("droppable err = %v", err)
	}
}
