package controlplane

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/SamuelMolling/godwit/internal/engine"
)

func newScratch(t *testing.T, ddl ...string) *pgx.Conn {
	t.Helper()
	conn, err := pgx.Connect(context.Background(), newDatabase(t, "exp"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = conn.Close(context.Background()) })
	for _, s := range ddl {
		if _, err := conn.Exec(context.Background(), s); err != nil {
			t.Fatalf("%s: %v", s, err)
		}
	}

	return conn
}

func directiveMigration(t *testing.T, up, down string) engine.Migration {
	t.Helper()
	migs, err := MigrationsFromFiles(map[string]string{
		"20260101000000_change.up.sql":   up,
		"20260101000000_change.down.sql": down,
	})
	if err != nil {
		t.Fatal(err)
	}

	return migs[0]
}

func expandOne(t *testing.T, conn engine.DB, up, down string) (Expansion, error) {
	t.Helper()

	return NewExpander().Expand(context.Background(), conn, directiveMigration(t, up, down))
}

func applyExpansion(t *testing.T, conn engine.DB, up, down string, exp Expansion) {
	t.Helper()
	p, err := ExpandPlan(engine.Plan{Migration: directiveMigration(t, up, down), Direction: engine.DirectionUp}, exp)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := applyPlans(context.Background(), conn, engine.Options{}, []engine.Plan{p}); err != nil {
		t.Fatal(err)
	}
}

const usersDDL = `CREATE TABLE public.users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email text NOT NULL,
	age integer NOT NULL
)`

const changeAge = "-- godwit: change-type users.age bigint\n"

const revertSentinel = "-- godwit: revert\n"

func TestExpandChangeType(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL, `INSERT INTO public.users (email, age) SELECT g::text, g FROM generate_series(1, 25) g`)
	exp, err := expandOne(t, conn, changeAge, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if got := exp.Contract(); got != 6 {
		t.Fatalf("contract starts at %d, phases %v", got, exp.Phase)
	}
	for _, want := range []string{
		`ALTER TABLE public.users ADD COLUMN age_new bigint;`,
		`CREATE FUNCTION public.users_age_sync() RETURNS trigger LANGUAGE plpgsql AS $godwit$ BEGIN SELECT age::bigint INTO new.age_new FROM (SELECT new.*) AS users; RETURN new; END $godwit$;`,
		`CREATE TRIGGER users_age_sync BEFORE INSERT OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.users_age_sync();`,
		`WHERE id > $1::bigint AND (age_new IS DISTINCT FROM age::bigint) ORDER BY id LIMIT 5000`,
		`ALTER TABLE public.users ADD CONSTRAINT users_age_new_not_null CHECK (age_new IS NOT NULL) NOT VALID;`,
		`ALTER TABLE public.users RENAME COLUMN age TO age_old;`,
		`ALTER TABLE public.users RENAME COLUMN age_new TO age;`,
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if len(exp.Retired) != 1 || exp.Retired[0].String() != "public.users.age_old" {
		t.Fatalf("retired = %+v", exp.Retired)
	}
	applyExpansion(t, conn, changeAge, revertSentinel, exp)

	var typ string
	var rows int
	if err := conn.QueryRow(context.Background(),
		`SELECT format_type(atttypid, atttypmod), (SELECT count(*) FROM public.users WHERE age = id)
		 FROM pg_attribute WHERE attrelid = 'public.users'::regclass AND attname = 'age'`).Scan(&typ, &rows); err != nil {
		t.Fatal(err)
	}
	if typ != "bigint" || rows != 25 {
		t.Fatalf("age is %s over %d migrated rows", typ, rows)
	}
}

func TestExpandChangeTypeKeepOldFalse(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "-- godwit: change-type users.age bigint keep-old=false\n"
	exp, err := expandOne(t, conn, up, "ALTER TABLE public.users DROP COLUMN age;\n")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, `ALTER TABLE public.users DROP COLUMN age_old;`) {
		t.Fatalf("keep-old=false must drop the old column:\n%s", exp.UpSQL)
	}
	if len(exp.Retired) != 0 || !strings.Contains(strings.Join(exp.Notes, "\n"), "becomes irreversible") {
		t.Fatalf("retired %+v notes %v", exp.Retired, exp.Notes)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "keep-old=false cannot be generated") {
		t.Fatalf("generated down = %v", err)
	}
}

func TestExpandChangeTypeUsingAndNotNullFlag(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.t (k uuid PRIMARY KEY DEFAULT gen_random_uuid(), n text)`)
	exp, err := expandOne(t, conn, "-- godwit: change-type t.n integer using='length(n)' not-null\n", revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "SELECT length(n) INTO new.n_new") || !strings.Contains(exp.UpSQL, "$1::uuid") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(exp.UpSQL, "ALTER TABLE public.t ALTER COLUMN n SET NOT NULL;") {
		t.Fatalf("not-null flag ignored:\n%s", exp.UpSQL)
	}
}

func TestExpandBackfill(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		`CREATE TABLE public.t (k text PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g::text, g, NULL FROM generate_series(1, 30) g`)
	up := "-- godwit: backfill t set='b = a * 2' where='b IS NULL' batch=7 pause=1ms\n"
	exp, err := expandOne(t, conn, up, "UPDATE public.t SET b = NULL;\n")
	if err != nil {
		t.Fatal(err)
	}
	if exp.Contract() != -1 || len(exp.Phase) != 1 || exp.Batches[0].Size != 7 || exp.Batches[0].Pause != time.Millisecond {
		t.Fatalf("phases %v batches %+v", exp.Phase, exp.Batches[0])
	}
	if !strings.Contains(exp.UpSQL, "$1::text") {
		t.Fatalf("text cursor:\n%s", exp.UpSQL)
	}
	applyExpansion(t, conn, up, "UPDATE public.t SET b = NULL;\n", exp)

	var done int
	if err := conn.QueryRow(context.Background(), `SELECT count(*) FROM public.t WHERE b = a * 2`).Scan(&done); err != nil {
		t.Fatal(err)
	}
	if done != 30 {
		t.Fatalf("%d of 30 rows backfilled", done)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil || !strings.Contains(err.Error(), "no generated inverse") {
		t.Fatalf("backfill revert = %v", err)
	}
}

// TestExpandBackfillResumesAfterCrash kills the backfill between batches and re-applies it; the second
// pass must start from the journalled cursor and leave every row correct.
func TestExpandBackfillResumesAfterCrash(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	conn := newScratch(t,
		`CREATE TABLE public.t (k bigint PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g, g, NULL FROM generate_series(1, 100) g`)
	up := "-- godwit: backfill t set='b = a * 2' where='b IS DISTINCT FROM a * 2' batch=10\n"
	down := "UPDATE public.t SET b = NULL;\n"
	exp, err := expandOne(t, conn, up, down)
	if err != nil {
		t.Fatal(err)
	}
	p, err := ExpandPlan(engine.Plan{Migration: directiveMigration(t, up, down), Direction: engine.DirectionUp}, exp)
	if err != nil {
		t.Fatal(err)
	}

	stop := make(chan struct{})
	crash := func(point engine.HookPoint, _ int) {
		if point == engine.HookAfterBatch {
			select {
			case <-stop:
			default:
				close(stop)
			}
		}
	}
	if _, err := applyPlans(ctx, conn, engine.Options{}, []engine.Plan{p}, engine.WithHook(crash)); err != nil {
		t.Fatal(err)
	}

	var cursor *string
	var doneRows int64
	if err := conn.QueryRow(ctx,
		`SELECT cursor, rows_done FROM godwit.journal WHERE stmt_idx = 0 ORDER BY recorded_at DESC LIMIT 1`).
		Scan(&cursor, &doneRows); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.Exec(ctx, `DELETE FROM godwit.migrations WHERE version = 20260101000000`); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.Exec(ctx, `UPDATE public.t SET b = NULL WHERE k > 50`); err != nil {
		t.Fatal(err)
	}
	if _, err := applyPlans(ctx, conn, engine.Options{}, []engine.Plan{p}); err != nil {
		t.Fatal(err)
	}
	var pending int
	if err := conn.QueryRow(ctx, `SELECT count(*) FROM public.t WHERE b IS DISTINCT FROM a * 2`).Scan(&pending); err != nil {
		t.Fatal(err)
	}
	if pending != 0 {
		t.Fatalf("%d rows left unbackfilled after resume", pending)
	}
}

func TestExpandRefusals(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		usersDDL,
		`CREATE TABLE public.orders (id bigint PRIMARY KEY, user_id bigint REFERENCES public.users (id))`,
		`CREATE TABLE public.taken (id bigint PRIMARY KEY, age integer, age_new integer)`,
		`CREATE TABLE public.nokey (age integer, tag text)`,
		`CREATE TABLE public.gen (id bigint PRIMARY KEY, age integer, twice integer GENERATED ALWAYS AS (age * 2) STORED)`,
		`CREATE TABLE public.parted (id bigint, age integer) PARTITION BY RANGE (id)`,
		`CREATE TABLE public.ref (id bigint PRIMARY KEY, age integer)`,
		`CREATE TABLE public.child (rid bigint REFERENCES public.ref (id))`,
		`CREATE VIEW public.v AS SELECT id, age FROM public.users`,
		`CREATE FUNCTION public.noisy(integer) RETURNS integer LANGUAGE sql VOLATILE AS $$ SELECT $1 $$`,
	)
	for name, tc := range map[string]struct{ up, want string }{
		"missing table":     {"-- godwit: change-type ghost.age bigint\n", "does not exist in the schema"},
		"missing column":    {"-- godwit: change-type users.ghost bigint\n", "does not exist in the schema"},
		"view":              {"-- godwit: change-type v.age bigint\n", "is not an ordinary table"},
		"partitioned":       {"-- godwit: change-type parted.age bigint\n", "is partitioned"},
		"identity":          {"-- godwit: change-type users.id bigint\n", "is an identity column"},
		"generated":         {"-- godwit: change-type gen.twice bigint\n", "is a generated column"},
		"foreign key":       {"-- godwit: change-type orders.user_id integer\n", "takes part in a foreign key"},
		"referenced key":    {"-- godwit: change-type ref.id integer\n", "takes part in a foreign key"},
		"collision":         {"-- godwit: change-type taken.age bigint\n", "age_new already exists"},
		"no primary key":    {"-- godwit: change-type nokey.age bigint\n", "has no single-column primary key"},
		"unknown key":       {"-- godwit: change-type users.age bigint key=ghost\n", "does not exist on"},
		"nullable key":      {"-- godwit: change-type nokey.age bigint key=tag\n", "is nullable"},
		"non unique key":    {"-- godwit: change-type users.age bigint key=email\n", "no single-column unique btree index"},
		"volatile using":    {"-- godwit: change-type users.age bigint using='noisy(age)'\n", "VOLATILE function"},
		"subquery using":    {"-- godwit: change-type users.age bigint using='(SELECT 1)'\n", "contains a subquery"},
		"other table using": {"-- godwit: change-type users.age bigint using='orders.id'\n", "only columns of users"},
		"two directives":    {"-- godwit: change-type users.age bigint\n-- godwit: change-type users.age numeric\n", "already the subject"},
		"destructive sql":   {"ALTER TABLE public.users DROP COLUMN email;\n-- godwit: change-type users.age bigint\n", "H003 in its own SQL"},
		"not expanded yet":  {"-- godwit: add-not-null users.email\n", "parsed but not expanded yet"},
		"split statement":   {"CREATE TABLE public.z (\n-- godwit: change-type users.age bigint\n a int);\n", "between whole statements"},
	} {
		t.Run(name, func(t *testing.T) {
			_, err := expandOne(t, conn, tc.up, "SELECT 1;\n")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
		})
	}
}

func TestExpandRefusesUnusableKeyType(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.t (k numeric PRIMARY KEY, age integer)`)
	if _, err := expandOne(t, conn, "-- godwit: change-type t.age bigint\n", "SELECT 1;\n"); err == nil ||
		!strings.Contains(err.Error(), "a batch cursor needs an integer, uuid or text key") {
		t.Fatalf("err = %v", err)
	}
}

func TestExpandRefusesUnparseableBody(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	if _, err := expandOne(t, conn, "NOT SQL AT ALL;\n-- godwit: change-type users.age bigint\n", "SELECT 1;\n"); err == nil ||
		!strings.Contains(err.Error(), "parse") {
		t.Fatalf("err = %v", err)
	}
}

func TestExpanderDefaults(t *testing.T) {
	t.Parallel()
	x := &Expander{}
	if got := x.batchSize(engine.Directive{Opts: map[string]string{}}); got != DefaultBatchSize {
		t.Fatalf("batch size = %d", got)
	}
	if got := pauseOf(engine.Directive{Opts: map[string]string{}}); got != 0 {
		t.Fatalf("pause = %s", got)
	}
	if got := cursorParam("nonsense"); got != "$1::text" {
		t.Fatalf("cursor param = %s", got)
	}
	if got := orEmpty(nil); got == nil || len(got) != 0 {
		t.Fatalf("orEmpty = %v", got)
	}
	if got := orEmpty(map[string]Expansion{"a": {}}); len(got) != 1 {
		t.Fatalf("orEmpty = %v", got)
	}
}

func TestExpandUsingShapes(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	exp, err := expandOne(t, conn,
		"-- godwit: change-type public.users.age numeric using='coalesce(abs(users.age), 0)::numeric + -1'\n", revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "coalesce(abs(users.age), 0)::numeric + -1") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	d := engine.Directive{Op: "change-type", Args: []string{"users.age", "bigint"}, Opts: map[string]string{"using": "1 +"}, Line: 1}
	if _, err := NewExpander().changeType(context.Background(), conn, d); err == nil ||
		!strings.Contains(err.Error(), "does not parse") {
		t.Fatalf("bad using = %v", err)
	}
}

func TestExpandBackfillWithoutWhere(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		`CREATE TABLE public.t (k bigint PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g, g, NULL FROM generate_series(1, 5) g`)
	up := "-- godwit: backfill public.t set='b = a'\n"
	down := "UPDATE public.t SET b = NULL;\n"
	exp, err := expandOne(t, conn, up, down)
	if err != nil {
		t.Fatal(err)
	}
	applyExpansion(t, conn, up, down, exp)
	var done int
	if err := conn.QueryRow(context.Background(), `SELECT count(*) FROM public.t WHERE b = a`).Scan(&done); err != nil {
		t.Fatal(err)
	}
	if done != 5 {
		t.Fatalf("%d of 5 rows backfilled", done)
	}
}

func TestExpandPlanRejectsBrokenExpansion(t *testing.T) {
	t.Parallel()
	p := engine.Plan{Migration: directiveMigration(t, changeAge, revertSentinel), Direction: engine.DirectionUp}
	if _, err := ExpandPlan(p, Expansion{ID: "x", UpSQL: "NOT SQL"}); err == nil ||
		!strings.Contains(err.Error(), "does not parse") {
		t.Fatalf("parse err = %v", err)
	}
	if _, err := ExpandPlan(p, Expansion{ID: "x", UpSQL: "SELECT 1; SELECT 2;", Phase: []string{""}}); err == nil ||
		!strings.Contains(err.Error(), "expansion has 2 statements, recorded 1") {
		t.Fatalf("count err = %v", err)
	}
	if _, err := ExpandUp([]engine.Plan{p}, map[string]Expansion{p.Migration.ID(): {UpSQL: "NOT SQL"}}); err == nil {
		t.Fatal("ExpandUp must report a broken expansion")
	}
	down := engine.Plan{Migration: p.Migration, Direction: engine.DirectionDown}
	out, err := ExpandDown([]engine.Plan{down}, map[string]Expansion{p.Migration.ID(): {DownHeld: "SELECT 1;"}}, true)
	if err != nil || len(out[0].Statements) != 1 || out[0].Statements[0].Hazards != nil {
		t.Fatalf("held down = %+v, err = %v", out, err)
	}
	if kept, err := ExpandDown([]engine.Plan{down}, map[string]Expansion{}, false); err != nil || len(kept[0].Statements) != 0 {
		t.Fatalf("hand-written down must be left alone: %+v %v", kept, err)
	}
	swap, err := ExpandDown([]engine.Plan{down}, map[string]Expansion{p.Migration.ID(): {DownSQL: "SELECT 1; SELECT 2;"}}, false)
	if err != nil || len(swap[0].Statements) != 2 {
		t.Fatalf("after-swap down = %+v, err = %v", swap, err)
	}
}

func TestRetiredHelper(t *testing.T) {
	t.Parallel()
	got := Retired(map[string]Expansion{
		"a": {Retired: []RetiredColumn{{Schema: "public", Table: "users", Column: "age_old"}}},
		"b": {},
	})
	if len(got) != 1 || got["a"][0].Column != "age_old" {
		t.Fatalf("retired = %+v", got)
	}
}

// flakyDB fails or rewrites the nth statement the expander runs, so every catalog probe's error branch
// is reachable without breaking the database itself.
type flakyDB struct {
	engine.DB
	n    *int
	fail int
	sub  string
}

type failRow struct{ err error }

func (r failRow) Scan(...any) error { return r.err }

func (f flakyDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	*f.n++
	if *f.n != f.fail {
		return f.DB.QueryRow(ctx, sql, args...)
	}
	if f.sub != "" {
		return f.DB.QueryRow(ctx, f.sub)
	}

	return failRow{errBoom}
}

func (f flakyDB) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	*f.n++
	if *f.n != f.fail {
		return f.DB.Query(ctx, sql, args...)
	}
	if f.sub != "" {
		return f.DB.Query(ctx, f.sub)
	}

	return nil, errBoom
}

func (f flakyDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	return f.DB.Exec(ctx, sql, args...)
}

func TestExpandCatalogErrors(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "-- godwit: change-type users.age bigint using='abs(age)'\n"
	for i := 1; i <= 7; i++ {
		n := 0
		_, err := expandOne(t, flakyDB{DB: conn, n: &n, fail: i}, up, revertSentinel)
		if err == nil {
			t.Fatalf("probe %d: expansion must fail", i)
		}
	}
	n := 0
	if _, err := expandOne(t, flakyDB{DB: conn, n: &n, fail: 3, sub: "SELECT 1, 2"}, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "read public.users columns") {
		t.Fatalf("collect err = %v", err)
	}
}

func TestExpandSplicesAroundOrdinarySQL(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "ALTER TABLE public.users ADD COLUMN nick text;\n" + changeAge + "CREATE INDEX users_nick_idx ON public.users (nick);\n"
	exp, err := expandOne(t, conn, up, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if exp.Phase[0] != "" || exp.Phase[1] != engine.PhaseExpand {
		t.Fatalf("phases = %v", exp.Phase)
	}
	if exp.Phase[len(exp.Phase)-7] != "" {
		t.Fatalf("file SQL after a directive keeps the migration's own phase: %v", exp.Phase)
	}
	applyExpansion(t, conn, up, revertSentinel, exp)
}

func TestExpandBackfillRefusals(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.nokey (a integer)`)
	for _, tc := range []struct{ up, want string }{
		{"-- godwit: backfill ghost set='a = 1'\n", "does not exist in the schema"},
		{"-- godwit: backfill nokey set='a = 1'\n", "has no single-column primary key"},
	} {
		if _, err := expandOne(t, conn, tc.up, "SELECT 1;\n"); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Fatalf("err = %v, want %q", err, tc.want)
		}
	}
}

func TestScanUsingWalksEveryShape(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL, `CREATE TABLE public.other (id bigint)`)
	if _, err := expandOne(t, conn, "-- godwit: change-type users.age bigint using='-age'\n", revertSentinel); err != nil {
		t.Fatalf("plain expression = %v", err)
	}
	for _, tc := range []struct{ using, want string }{
		{"abs(other.id)", "only columns of users"},
		{"other.id::bigint", "only columns of users"},
		{"coalesce(other.id, 0)", "only columns of users"},
		{"age + other.id", "only columns of users"},
		{"other.id + age", "only columns of users"},
		{"abs((SELECT 1))", "contains a subquery"},
	} {
		up := "-- godwit: change-type users.age bigint using='" + tc.using + "'\n"
		if _, err := expandOne(t, conn, up, revertSentinel); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Fatalf("using=%s: err = %v", tc.using, err)
		}
	}
}
