package controlplane

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"

	"github.com/SamuelMolling/godwit/internal/engine"
)

func newScratch(t *testing.T, ddl ...string) *pgx.Conn {
	t.Helper()
	conn, err := pgx.Connect(context.Background(), newDatabase(t, "exp"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = conn.Close(context.Background()) })
	for _, s := range ddl {
		if _, err := conn.Exec(context.Background(), s); err != nil {
			t.Fatalf("%s: %v", s, err)
		}
	}

	return conn
}

func directiveMigration(t *testing.T, up, down string) engine.Migration {
	t.Helper()
	migs, err := MigrationsFromFiles(map[string]string{
		"20260101000000_change.up.sql":   up,
		"20260101000000_change.down.sql": down,
	})
	if err != nil {
		t.Fatal(err)
	}

	return migs[0]
}

func expandOne(t *testing.T, conn engine.DB, up, down string) (Expansion, error) {
	t.Helper()

	return NewExpander().Expand(context.Background(), conn, directiveMigration(t, up, down))
}

func applyExpansion(t *testing.T, conn engine.DB, up, down string, exp Expansion) {
	t.Helper()
	p, err := ExpandPlan(engine.Plan{Migration: directiveMigration(t, up, down), Direction: engine.DirectionUp}, exp)
	if err != nil {
		t.Fatal(err)
	}
	boom := func(context.Context, engine.Result) error { return errBoom }
	if _, err := applyPlans(context.Background(), conn, engine.Options{}, []engine.Plan{p}, boom); !errors.Is(err, errBoom) {
		t.Fatalf("a ledger write that fails must stop the run: %v", err)
	}
	if _, err := applyPlans(context.Background(), conn, engine.Options{}, []engine.Plan{p}, nil); err != nil {
		t.Fatal(err)
	}
}

const usersDDL = `CREATE TABLE public.users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email text NOT NULL,
	age integer NOT NULL
)`

const changeAge = "-- godwit: change-type users.age bigint\n"

const revertSentinel = "-- godwit: revert\n"

func TestExpandChangeType(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL, `INSERT INTO public.users (email, age) SELECT g::text, g FROM generate_series(1, 25) g`)
	exp, err := expandOne(t, conn, changeAge, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if got := exp.Contract(); got != 6 {
		t.Fatalf("contract starts at %d, phases %v", got, exp.Phase)
	}
	for _, want := range []string{
		`ALTER TABLE public.users ADD COLUMN age_new bigint;`,
		`CREATE FUNCTION public.users_age_sync() RETURNS trigger LANGUAGE plpgsql AS $godwit$ BEGIN SELECT age::bigint INTO new.age_new FROM (SELECT new.*) AS users; RETURN new; END $godwit$;`,
		`CREATE TRIGGER users_age_sync BEFORE INSERT OR UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.users_age_sync();`,
		`WHERE id > $1::bigint AND (age_new IS DISTINCT FROM age::bigint) ORDER BY id LIMIT 5000`,
		`ALTER TABLE public.users ADD CONSTRAINT users_age_new_not_null CHECK (age_new IS NOT NULL) NOT VALID;`,
		`ALTER TABLE public.users RENAME COLUMN age TO age_old;`,
		`ALTER TABLE public.users RENAME COLUMN age_new TO age;`,
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if len(exp.Retired) != 1 || exp.Retired[0].String() != "public.users.age_old" {
		t.Fatalf("retired = %+v", exp.Retired)
	}
	applyExpansion(t, conn, changeAge, revertSentinel, exp)

	var typ string
	var rows int
	if err := conn.QueryRow(context.Background(),
		`SELECT format_type(atttypid, atttypmod), (SELECT count(*) FROM public.users WHERE age = id)
		 FROM pg_attribute WHERE attrelid = 'public.users'::regclass AND attname = 'age'`).Scan(&typ, &rows); err != nil {
		t.Fatal(err)
	}
	if typ != "bigint" || rows != 25 {
		t.Fatalf("age is %s over %d migrated rows", typ, rows)
	}
}

func TestExpandChangeTypeKeepOldFalse(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "-- godwit: change-type users.age bigint keep-old=false\n"
	exp, err := expandOne(t, conn, up, "ALTER TABLE public.users DROP COLUMN age;\n")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, `ALTER TABLE public.users DROP COLUMN age_old;`) {
		t.Fatalf("keep-old=false must drop the old column:\n%s", exp.UpSQL)
	}
	if len(exp.Retired) != 0 || !strings.Contains(strings.Join(exp.Notes, "\n"), "becomes irreversible") {
		t.Fatalf("retired %+v notes %v", exp.Retired, exp.Notes)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "keep-old=false cannot be generated") {
		t.Fatalf("generated down = %v", err)
	}
}

func TestExpandChangeTypeUsingAndNotNullFlag(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.t (k uuid PRIMARY KEY DEFAULT gen_random_uuid(), n text)`)
	exp, err := expandOne(t, conn, "-- godwit: change-type t.n integer using='length(n)' not-null\n", revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "SELECT length(n) INTO new.n_new") || !strings.Contains(exp.UpSQL, "$1::uuid") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(exp.UpSQL, "ALTER TABLE public.t ALTER COLUMN n SET NOT NULL;") {
		t.Fatalf("not-null flag ignored:\n%s", exp.UpSQL)
	}
}

func TestExpandBackfill(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		`CREATE TABLE public.t (k text PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g::text, g, NULL FROM generate_series(1, 30) g`)
	up := "-- godwit: backfill t set='b = a * 2' where='b IS NULL' batch=7 pause=1ms\n"
	exp, err := expandOne(t, conn, up, "UPDATE public.t SET b = NULL;\n")
	if err != nil {
		t.Fatal(err)
	}
	if exp.Contract() != -1 || len(exp.Phase) != 1 || exp.Batches[0].Size != 7 || exp.Batches[0].Pause != time.Millisecond {
		t.Fatalf("phases %v batches %+v", exp.Phase, exp.Batches[0])
	}
	if !strings.Contains(exp.UpSQL, "$1::text") {
		t.Fatalf("text cursor:\n%s", exp.UpSQL)
	}
	applyExpansion(t, conn, up, "UPDATE public.t SET b = NULL;\n", exp)

	var done int
	if err := conn.QueryRow(context.Background(), `SELECT count(*) FROM public.t WHERE b = a * 2`).Scan(&done); err != nil {
		t.Fatal(err)
	}
	if done != 30 {
		t.Fatalf("%d of 30 rows backfilled", done)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil || !strings.Contains(err.Error(), "no generated inverse") {
		t.Fatalf("backfill revert = %v", err)
	}
}

// TestExpandBackfillResumesAfterCrash kills the backfill between batches and re-applies it; the second
// pass must start from the journalled cursor and leave every row correct.
func TestExpandBackfillResumesAfterCrash(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	conn := newScratch(t,
		`CREATE TABLE public.t (k bigint PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g, g, NULL FROM generate_series(1, 100) g`)
	up := "-- godwit: backfill t set='b = a * 2' where='b IS DISTINCT FROM a * 2' batch=10\n"
	down := "UPDATE public.t SET b = NULL;\n"
	exp, err := expandOne(t, conn, up, down)
	if err != nil {
		t.Fatal(err)
	}
	p, err := ExpandPlan(engine.Plan{Migration: directiveMigration(t, up, down), Direction: engine.DirectionUp}, exp)
	if err != nil {
		t.Fatal(err)
	}

	stop := make(chan struct{})
	crash := func(point engine.HookPoint, _ int) {
		if point == engine.HookAfterBatch {
			select {
			case <-stop:
			default:
				close(stop)
			}
		}
	}
	if _, err := applyPlans(ctx, conn, engine.Options{}, []engine.Plan{p}, nil, engine.WithHook(crash)); err != nil {
		t.Fatal(err)
	}

	var cursor *string
	var doneRows int64
	if err := conn.QueryRow(ctx,
		`SELECT cursor, rows_done FROM godwit.journal WHERE stmt_idx = 0 ORDER BY recorded_at DESC LIMIT 1`).
		Scan(&cursor, &doneRows); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.Exec(ctx, `DELETE FROM godwit.migrations WHERE version = 20260101000000`); err != nil {
		t.Fatal(err)
	}
	if _, err := conn.Exec(ctx, `UPDATE public.t SET b = NULL WHERE k > 50`); err != nil {
		t.Fatal(err)
	}
	if _, err := applyPlans(ctx, conn, engine.Options{}, []engine.Plan{p}, nil); err != nil {
		t.Fatal(err)
	}
	var pending int
	if err := conn.QueryRow(ctx, `SELECT count(*) FROM public.t WHERE b IS DISTINCT FROM a * 2`).Scan(&pending); err != nil {
		t.Fatal(err)
	}
	if pending != 0 {
		t.Fatalf("%d rows left unbackfilled after resume", pending)
	}
}

func TestExpandRefusals(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		usersDDL,
		`CREATE TABLE public.orders (id bigint PRIMARY KEY, user_id bigint REFERENCES public.users (id))`,
		`CREATE TABLE public.taken (id bigint PRIMARY KEY, age integer, age_new integer)`,
		`CREATE TABLE public.nokey (age integer, tag text)`,
		`CREATE TABLE public.gen (id bigint PRIMARY KEY, age integer, twice integer GENERATED ALWAYS AS (age * 2) STORED)`,
		`CREATE TABLE public.parted (id bigint, age integer) PARTITION BY RANGE (id)`,
		`CREATE TABLE public.ref (id bigint PRIMARY KEY, age integer)`,
		`CREATE TABLE public.child (rid bigint REFERENCES public.ref (id))`,
		`CREATE VIEW public.v AS SELECT id, email FROM public.users`,
		`CREATE FUNCTION public.noisy(integer) RETURNS integer LANGUAGE sql VOLATILE AS $$ SELECT $1 $$`,
	)
	for name, tc := range map[string]struct{ up, want string }{
		"missing table":     {"-- godwit: change-type ghost.age bigint\n", "does not exist in the schema"},
		"missing column":    {"-- godwit: change-type users.ghost bigint\n", "does not exist in the schema"},
		"view":              {"-- godwit: change-type v.email text\n", "is not an ordinary table"},
		"partitioned":       {"-- godwit: change-type parted.age bigint\n", "is partitioned"},
		"identity":          {"-- godwit: change-type users.id bigint\n", "is an identity column"},
		"generated":         {"-- godwit: change-type gen.twice bigint\n", "is a generated column"},
		"foreign key":       {"-- godwit: change-type orders.user_id integer\n", "takes part in a foreign key"},
		"referenced key":    {"-- godwit: change-type ref.id integer\n", "takes part in a foreign key"},
		"collision":         {"-- godwit: change-type taken.age bigint\n", "age_new already exists"},
		"no primary key":    {"-- godwit: change-type nokey.age bigint\n", "has no single-column primary key"},
		"unknown key":       {"-- godwit: change-type users.age bigint key=ghost\n", "does not exist on"},
		"nullable key":      {"-- godwit: change-type nokey.age bigint key=tag\n", "is nullable"},
		"non unique key":    {"-- godwit: change-type users.age bigint key=email\n", "no single-column unique btree index"},
		"volatile using":    {"-- godwit: change-type users.age bigint using='noisy(age)'\n", "VOLATILE function"},
		"subquery using":    {"-- godwit: change-type users.age bigint using='(SELECT 1)'\n", "contains a subquery"},
		"other table using": {"-- godwit: change-type users.age bigint using='orders.id'\n", "only columns of users"},
		"two directives":    {"-- godwit: change-type users.age bigint\n-- godwit: change-type users.age numeric\n", "already the subject"},
		"destructive sql":   {"ALTER TABLE public.users DROP COLUMN email;\n-- godwit: change-type users.age bigint\n", "H003 in its own SQL"},
		"split statement":   {"CREATE TABLE public.z (\n-- godwit: change-type users.age bigint\n a int);\n", "between whole statements"},
	} {
		t.Run(name, func(t *testing.T) {
			_, err := expandOne(t, conn, tc.up, "SELECT 1;\n")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
		})
	}
}

func TestExpandRefusesUnusableKeyType(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.t (k numeric PRIMARY KEY, age integer)`)
	if _, err := expandOne(t, conn, "-- godwit: change-type t.age bigint\n", "SELECT 1;\n"); err == nil ||
		!strings.Contains(err.Error(), "a batch cursor needs an integer, uuid or text key") {
		t.Fatalf("err = %v", err)
	}
}

func TestExpandRefusesUnparseableBody(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	if _, err := expandOne(t, conn, "NOT SQL AT ALL;\n-- godwit: change-type users.age bigint\n", "SELECT 1;\n"); err == nil ||
		!strings.Contains(err.Error(), "parse") {
		t.Fatalf("err = %v", err)
	}
}

func TestExpanderDefaults(t *testing.T) {
	t.Parallel()
	x := &Expander{}
	if got := x.batchSize(engine.Directive{Opts: map[string]string{}}); got != DefaultBatchSize {
		t.Fatalf("batch size = %d", got)
	}
	if got := pauseOf(engine.Directive{Opts: map[string]string{}}); got != 0 {
		t.Fatalf("pause = %s", got)
	}
	if got := cursorParam("nonsense"); got != "$1::text" {
		t.Fatalf("cursor param = %s", got)
	}
	if got := orEmpty(nil); got == nil || len(got) != 0 {
		t.Fatalf("orEmpty = %v", got)
	}
	if got := orEmpty(map[string]Expansion{"a": {}}); len(got) != 1 {
		t.Fatalf("orEmpty = %v", got)
	}
}

func TestExpandUsingShapes(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	exp, err := expandOne(t, conn,
		"-- godwit: change-type public.users.age numeric using='coalesce(abs(users.age), 0)::numeric + -1'\n", revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "coalesce(abs(users.age), 0)::numeric + -1") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	d := engine.Directive{Op: "change-type", Args: []string{"users.age", "bigint"}, Opts: map[string]string{"using": "1 +"}, Line: 1}
	if _, err := NewExpander().changeType(context.Background(), conn, d); err == nil ||
		!strings.Contains(err.Error(), "does not parse") {
		t.Fatalf("bad using = %v", err)
	}
}

func TestExpandBackfillWithoutWhere(t *testing.T) {
	t.Parallel()
	conn := newScratch(t,
		`CREATE TABLE public.t (k bigint PRIMARY KEY, a integer, b integer)`,
		`INSERT INTO public.t SELECT g, g, NULL FROM generate_series(1, 5) g`)
	up := "-- godwit: backfill public.t set='b = a'\n"
	down := "UPDATE public.t SET b = NULL;\n"
	exp, err := expandOne(t, conn, up, down)
	if err != nil {
		t.Fatal(err)
	}
	applyExpansion(t, conn, up, down, exp)
	var done int
	if err := conn.QueryRow(context.Background(), `SELECT count(*) FROM public.t WHERE b = a`).Scan(&done); err != nil {
		t.Fatal(err)
	}
	if done != 5 {
		t.Fatalf("%d of 5 rows backfilled", done)
	}
}

func TestExpandPlanRejectsBrokenExpansion(t *testing.T) {
	t.Parallel()
	p := engine.Plan{Migration: directiveMigration(t, changeAge, revertSentinel), Direction: engine.DirectionUp}
	if _, err := ExpandPlan(p, Expansion{ID: "x", UpSQL: "NOT SQL"}); err == nil ||
		!strings.Contains(err.Error(), "does not parse") {
		t.Fatalf("parse err = %v", err)
	}
	if _, err := ExpandPlan(p, Expansion{ID: "x", UpSQL: "SELECT 1; SELECT 2;", Phase: []string{""}}); err == nil ||
		!strings.Contains(err.Error(), "expansion has 2 statements, recorded 1") {
		t.Fatalf("count err = %v", err)
	}
	if _, err := ExpandUp([]engine.Plan{p}, map[string]Expansion{p.Migration.ID(): {UpSQL: "NOT SQL"}}); err == nil {
		t.Fatal("ExpandUp must report a broken expansion")
	}
	down := engine.Plan{Migration: p.Migration, Direction: engine.DirectionDown}
	held := []RunMigration{{Migration: p.Migration.ID(), Held: true, Expansion: &Expansion{DownHeld: "SELECT 1;"}}}
	out, err := ExpandDown([]engine.Plan{down}, held)
	if err != nil || len(out[0].Statements) != 1 || out[0].Statements[0].Hazards != nil {
		t.Fatalf("held down = %+v, err = %v", out, err)
	}
	kept, err := ExpandDown([]engine.Plan{down}, []RunMigration{{Migration: p.Migration.ID()}})
	if err != nil || len(kept[0].Statements) != 0 {
		t.Fatalf("hand-written down must be left alone: %+v %v", kept, err)
	}
	swap, err := ExpandDown([]engine.Plan{down}, []RunMigration{
		{Migration: p.Migration.ID(), Expansion: &Expansion{DownSQL: "SELECT 1; SELECT 2;"}},
	})
	if err != nil || len(swap[0].Statements) != 2 {
		t.Fatalf("after-swap down = %+v, err = %v", swap, err)
	}
}

func TestRetiredHelper(t *testing.T) {
	t.Parallel()
	got := Retired(map[string]Expansion{
		"a": {Retired: []RetiredColumn{{Schema: "public", Table: "users", Column: "age_old"}}},
		"b": {},
	})
	if len(got) != 1 || got["a"][0].Column != "age_old" {
		t.Fatalf("retired = %+v", got)
	}
}

// flakyDB fails or rewrites the nth statement the expander runs, so every catalog probe's error branch
// is reachable without breaking the database itself.
type flakyDB struct {
	engine.DB
	n    *int
	fail int
	sub  string
}

type failRow struct{ err error }

func (r failRow) Scan(...any) error { return r.err }

func (f flakyDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	*f.n++
	if *f.n != f.fail {
		return f.DB.QueryRow(ctx, sql, args...)
	}
	if f.sub != "" {
		return f.DB.QueryRow(ctx, f.sub)
	}

	return failRow{errBoom}
}

func (f flakyDB) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	*f.n++
	if *f.n != f.fail {
		return f.DB.Query(ctx, sql, args...)
	}
	if f.sub != "" {
		return f.DB.Query(ctx, f.sub)
	}

	return nil, errBoom
}

func (f flakyDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	return f.DB.Exec(ctx, sql, args...)
}

func TestExpandCatalogErrors(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "-- godwit: change-type users.age bigint using='abs(age)'\n"
	for i := 1; i <= 7; i++ {
		n := 0
		_, err := expandOne(t, flakyDB{DB: conn, n: &n, fail: i}, up, revertSentinel)
		if err == nil {
			t.Fatalf("probe %d: expansion must fail", i)
		}
	}
	n := 0
	if _, err := expandOne(t, flakyDB{DB: conn, n: &n, fail: 3, sub: "SELECT 1, 2"}, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "read public.users columns") {
		t.Fatalf("collect err = %v", err)
	}
}

func TestExpandSplicesAroundOrdinarySQL(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL)
	up := "ALTER TABLE public.users ADD COLUMN nick text;\n" + changeAge + "CREATE INDEX users_nick_idx ON public.users (nick);\n"
	exp, err := expandOne(t, conn, up, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	if exp.Phase[0] != "" || exp.Phase[1] != engine.PhaseExpand {
		t.Fatalf("phases = %v", exp.Phase)
	}
	if exp.Phase[len(exp.Phase)-7] != "" {
		t.Fatalf("file SQL after a directive keeps the migration's own phase: %v", exp.Phase)
	}
	applyExpansion(t, conn, up, revertSentinel, exp)
}

func TestExpandBackfillRefusals(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, `CREATE TABLE public.nokey (a integer)`)
	for _, tc := range []struct{ up, want string }{
		{"-- godwit: backfill ghost set='a = 1'\n", "does not exist in the schema"},
		{"-- godwit: backfill nokey set='a = 1'\n", "has no single-column primary key"},
	} {
		if _, err := expandOne(t, conn, tc.up, "SELECT 1;\n"); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Fatalf("err = %v, want %q", err, tc.want)
		}
	}
}

func TestScanUsingWalksEveryShape(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, usersDDL, `CREATE TABLE public.other (id bigint)`)
	if _, err := expandOne(t, conn, "-- godwit: change-type users.age bigint using='-age'\n", revertSentinel); err != nil {
		t.Fatalf("plain expression = %v", err)
	}
	for _, tc := range []struct{ using, want string }{
		{"abs(other.id)", "only columns of users"},
		{"other.id::bigint", "only columns of users"},
		{"coalesce(other.id, 0)", "only columns of users"},
		{"age + other.id", "only columns of users"},
		{"other.id + age", "only columns of users"},
		{"abs((SELECT 1))", "contains a subquery"},
	} {
		up := "-- godwit: change-type users.age bigint using='" + tc.using + "'\n"
		if _, err := expandOne(t, conn, up, revertSentinel); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Fatalf("using=%s: err = %v", tc.using, err)
		}
	}
}

const shopDDL = `CREATE TABLE public.shop (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag text,
	price integer
)`

func expandAndApply(t *testing.T, conn engine.DB, up string) Expansion {
	t.Helper()
	exp, err := expandOne(t, conn, up, revertSentinel)
	if err != nil {
		t.Fatal(err)
	}
	applyExpansion(t, conn, up, revertSentinel, exp)

	return exp
}

func columnIsNotNull(t *testing.T, conn engine.DB, rel, column string) bool {
	t.Helper()
	var notNull bool
	if err := conn.QueryRow(context.Background(),
		`SELECT attnotnull FROM pg_attribute WHERE attrelid = to_regclass($1) AND attname = $2`,
		rel, column).Scan(&notNull); err != nil {
		t.Fatal(err)
	}

	return notNull
}

func TestExpandAddNotNull(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) SELECT g::text, g FROM generate_series(1, 5) g`)
	exp := expandAndApply(t, conn, "-- godwit: add-not-null shop.tag\n")
	for _, want := range []string{
		`ALTER TABLE public.shop ADD CONSTRAINT tag_not_null CHECK (tag IS NOT NULL) NOT VALID;`,
		`ALTER TABLE public.shop VALIDATE CONSTRAINT tag_not_null;`,
		`ALTER TABLE public.shop ALTER COLUMN tag SET NOT NULL;`,
		`ALTER TABLE public.shop DROP CONSTRAINT tag_not_null;`,
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if exp.Contract() != -1 || len(exp.Phase) != 4 {
		t.Fatalf("phases = %v", exp.Phase)
	}
	if !columnIsNotNull(t, conn, "public.shop", "tag") {
		t.Fatal("tag must be NOT NULL after the expansion")
	}
	if !strings.Contains(exp.DownSQL, `ALTER TABLE public.shop ALTER COLUMN tag DROP NOT NULL;`) {
		t.Fatalf("down = %q", exp.DownSQL)
	}
}

func TestExpandAddNotNullReusesAnEquivalentCheck(t *testing.T) {
	t.Parallel()
	for name, tc := range map[string]struct {
		ddl   string
		want  []string
		avoid []string
	}{
		"godwit's own, not yet validated": {
			ddl:   `ALTER TABLE public.shop ADD CONSTRAINT tag_not_null CHECK (tag IS NOT NULL) NOT VALID`,
			want:  []string{"VALIDATE CONSTRAINT tag_not_null;", "DROP CONSTRAINT tag_not_null;"},
			avoid: []string{"ADD CONSTRAINT tag_not_null"},
		},
		"godwit's own, already validated": {
			ddl:   `ALTER TABLE public.shop ADD CONSTRAINT tag_not_null CHECK (tag IS NOT NULL)`,
			want:  []string{"ALTER COLUMN tag SET NOT NULL;", "DROP CONSTRAINT tag_not_null;"},
			avoid: []string{"ADD CONSTRAINT tag_not_null", "VALIDATE CONSTRAINT"},
		},
		"someone else's": {
			ddl:   `ALTER TABLE public.shop ADD CONSTRAINT shop_tag_present CHECK (tag IS NOT NULL) NOT VALID`,
			want:  []string{"VALIDATE CONSTRAINT shop_tag_present;", "ALTER COLUMN tag SET NOT NULL;"},
			avoid: []string{"ADD CONSTRAINT", "DROP CONSTRAINT"},
		},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag) VALUES ('a')`, tc.ddl)
			exp := expandAndApply(t, conn, "-- godwit: add-not-null shop.tag\n")
			for _, w := range tc.want {
				if !strings.Contains(exp.UpSQL, w) {
					t.Fatalf("expansion is missing %q:\n%s", w, exp.UpSQL)
				}
			}
			for _, a := range tc.avoid {
				if strings.Contains(exp.UpSQL, a) {
					t.Fatalf("expansion must not carry %q:\n%s", a, exp.UpSQL)
				}
			}
			if !strings.Contains(strings.Join(exp.Notes, "\n"), "reuses the CHECK") {
				t.Fatalf("notes = %v", exp.Notes)
			}
			if !columnIsNotNull(t, conn, "public.shop", "tag") {
				t.Fatal("tag must be NOT NULL after the expansion")
			}
		})
	}
}

func TestExpandAddColumn(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) VALUES ('a', 1)`)
	exp := expandAndApply(t, conn, "-- godwit: add-column shop.nick text\n")
	if !strings.Contains(exp.UpSQL, "ALTER TABLE public.shop ADD COLUMN nick text;") || len(exp.Phase) != 1 {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(exp.DownSQL, "ALTER TABLE public.shop DROP COLUMN IF EXISTS nick;") {
		t.Fatalf("down = %q", exp.DownSQL)
	}
}

func TestExpandAddColumnNotNullBackfills(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) SELECT g::text, g FROM generate_series(1, 12) g`)
	exp := expandAndApply(t, conn, "-- godwit: add-column shop.zone text default='''eu''' not-null\n")
	for _, want := range []string{
		"ALTER TABLE public.shop ADD COLUMN zone text;",
		"ALTER TABLE public.shop ALTER COLUMN zone SET DEFAULT 'eu';",
		"SET zone = 'eu' FROM b",
		"ALTER TABLE public.shop ADD CONSTRAINT zone_not_null CHECK (zone IS NOT NULL) NOT VALID;",
		"ALTER TABLE public.shop ALTER COLUMN zone SET NOT NULL;",
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if exp.Batches[2] == nil || exp.Batches[2].Key != "id" {
		t.Fatalf("batches = %+v", exp.Batches)
	}
	var filled int
	if err := conn.QueryRow(context.Background(), `SELECT count(*) FROM public.shop WHERE zone = 'eu'`).Scan(&filled); err != nil {
		t.Fatal(err)
	}
	if filled != 12 || !columnIsNotNull(t, conn, "public.shop", "zone") {
		t.Fatalf("%d of 12 rows filled", filled)
	}
}

func TestExpandAddIndex(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) SELECT g::text, g FROM generate_series(1, 4) g`)
	exp := expandAndApply(t, conn, "-- godwit: add-index shop (tag, price)\n")
	if !strings.Contains(exp.UpSQL, "CREATE INDEX CONCURRENTLY shop_tag_price_idx ON public.shop (tag, price);") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(exp.DownSQL, "DROP INDEX CONCURRENTLY IF EXISTS public.shop_tag_price_idx;") {
		t.Fatalf("down = %q", exp.DownSQL)
	}
}

func TestExpandAddIndexUniquePartialExpression(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) SELECT g::text, g FROM generate_series(1, 4) g`)
	exp := expandAndApply(t, conn,
		"-- godwit: add-index shop (lower(tag)) name=shop_lower_idx using=btree where='price > 0' unique\n")
	if !strings.Contains(exp.UpSQL,
		"CREATE UNIQUE INDEX CONCURRENTLY shop_lower_idx ON public.shop USING btree (lower(tag)) WHERE price > 0;") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	var valid bool
	if err := conn.QueryRow(context.Background(),
		`SELECT indisvalid FROM pg_index WHERE indexrelid = 'public.shop_lower_idx'::regclass`).Scan(&valid); err != nil {
		t.Fatal(err)
	}
	if !valid {
		t.Fatal("the index must be valid after the expansion")
	}
}

func TestExpandAddIndexDropsAnInvalidLeftover(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	conn := newScratch(t,
		`CREATE TABLE public.dup (id bigint PRIMARY KEY, tag text)`,
		`INSERT INTO public.dup VALUES (1, 'a'), (2, 'a')`)
	if _, err := conn.Exec(ctx, `CREATE UNIQUE INDEX CONCURRENTLY dup_tag_idx ON public.dup (tag)`); err == nil {
		t.Fatal("the duplicate rows must make the concurrent build fail and leave an invalid index")
	}
	exp := expandAndApply(t, conn, "-- godwit: add-index dup (tag)\n")
	if !strings.HasPrefix(exp.Phase[0], engine.PhaseExpand) || len(exp.Phase) != 2 {
		t.Fatalf("phases = %v", exp.Phase)
	}
	if !strings.Contains(exp.UpSQL, "DROP INDEX CONCURRENTLY IF EXISTS public.dup_tag_idx;\nCREATE INDEX CONCURRENTLY dup_tag_idx") {
		t.Fatalf("the invalid leftover must be dropped first:\n%s", exp.UpSQL)
	}
	if !strings.Contains(strings.Join(exp.Notes, "\n"), "interrupted index build") {
		t.Fatalf("notes = %v", exp.Notes)
	}
	var valid bool
	if err := conn.QueryRow(ctx,
		`SELECT indisvalid FROM pg_index WHERE indexrelid = 'public.dup_tag_idx'::regclass`).Scan(&valid); err != nil {
		t.Fatal(err)
	}
	if !valid {
		t.Fatal("the rebuilt index must be valid")
	}
}

func TestExpandDropIndex(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `CREATE INDEX shop_tag_idx ON public.shop (tag)`)
	up := "-- godwit: drop-index shop_tag_idx\n"
	exp, err := expandOne(t, conn, up, "CREATE INDEX shop_tag_idx ON public.shop (tag);\n")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(exp.UpSQL, "DROP INDEX CONCURRENTLY IF EXISTS public.shop_tag_idx;") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "no generated inverse") {
		t.Fatalf("generated down = %v", err)
	}
	applyExpansion(t, conn, up, "CREATE INDEX shop_tag_idx ON public.shop (tag);\n", exp)
	var left int
	if err := conn.QueryRow(context.Background(),
		`SELECT count(*) FROM pg_class WHERE relname = 'shop_tag_idx'`).Scan(&left); err != nil {
		t.Fatal(err)
	}
	if left != 0 {
		t.Fatal("the index must be gone")
	}
}

const itemDDL = `CREATE TABLE public.item (id bigint PRIMARY KEY, shop_id bigint)`

func TestExpandAddForeignKey(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, itemDDL,
		`INSERT INTO public.shop (tag) VALUES ('a')`,
		`INSERT INTO public.item VALUES (1, 1)`)
	exp := expandAndApply(t, conn, "-- godwit: add-fk item.shop_id -> shop.id on-delete=cascade\n")
	for _, want := range []string{
		"ALTER TABLE public.item ADD CONSTRAINT item_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.shop (id) ON DELETE CASCADE NOT VALID;",
		"ALTER TABLE public.item VALIDATE CONSTRAINT item_shop_id_fkey;",
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if !strings.Contains(exp.DownSQL, "ALTER TABLE public.item DROP CONSTRAINT IF EXISTS item_shop_id_fkey;") {
		t.Fatalf("down = %q", exp.DownSQL)
	}
	var validated bool
	if err := conn.QueryRow(context.Background(),
		`SELECT convalidated FROM pg_constraint WHERE conname = 'item_shop_id_fkey'`).Scan(&validated); err != nil {
		t.Fatal(err)
	}
	if !validated {
		t.Fatal("the foreign key must end validated")
	}
}

func TestExpandAddForeignKeyNamed(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, itemDDL)
	exp := expandAndApply(t, conn, "-- godwit: add-fk public.item.shop_id -> public.shop.id name=item_shop\n")
	if !strings.Contains(exp.UpSQL, "ADD CONSTRAINT item_shop FOREIGN KEY (shop_id) REFERENCES public.shop (id) NOT VALID;") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
}

func TestExpandAddCheck(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag, price) VALUES ('a', 3)`)
	exp := expandAndApply(t, conn, "-- godwit: add-check shop shop_price_check 'price > 0'\n")
	for _, want := range []string{
		"ALTER TABLE public.shop ADD CONSTRAINT shop_price_check CHECK (price > 0) NOT VALID;",
		"ALTER TABLE public.shop VALIDATE CONSTRAINT shop_price_check;",
	} {
		if !strings.Contains(exp.UpSQL, want) {
			t.Fatalf("expansion is missing %q:\n%s", want, exp.UpSQL)
		}
	}
	if !strings.Contains(exp.DownSQL, "DROP CONSTRAINT IF EXISTS shop_price_check;") {
		t.Fatalf("down = %q", exp.DownSQL)
	}
}

func TestExpandDropColumnIsContract(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, `INSERT INTO public.shop (tag) VALUES ('a')`)
	up := "-- godwit: drop-column shop.price\n"
	exp, err := expandOne(t, conn, up, "ALTER TABLE public.shop ADD COLUMN price integer;\n")
	if err != nil {
		t.Fatal(err)
	}
	if exp.Contract() != 0 || len(exp.Phase) != 1 {
		t.Fatalf("drop-column belongs to the contract phase: %v", exp.Phase)
	}
	if !strings.Contains(exp.UpSQL, "ALTER TABLE public.shop DROP COLUMN price;") {
		t.Fatalf("expansion:\n%s", exp.UpSQL)
	}
	if !strings.Contains(strings.Join(exp.Notes, "\n"), "no longer reads it first") {
		t.Fatalf("notes = %v", exp.Notes)
	}
	if _, err := expandOne(t, conn, up, revertSentinel); err == nil ||
		!strings.Contains(err.Error(), "the rows go with the column") {
		t.Fatalf("generated down = %v", err)
	}
}

func TestExpandSimpleRefusals(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL,
		`CREATE TABLE public.item (id bigint PRIMARY KEY, shop_id bigint, note text NOT NULL)`,
		`CREATE TABLE public.nokey (a integer, b text)`,
		`CREATE INDEX shop_tag_idx ON public.shop (tag)`,
		`CREATE UNIQUE INDEX item_note_key ON public.item (note)`,
		`ALTER TABLE public.item ADD CONSTRAINT item_note_uq UNIQUE USING INDEX item_note_key`,
	)
	for name, tc := range map[string]struct{ up, want string }{
		"not null on a missing column": {"-- godwit: add-not-null shop.ghost\n", "does not exist in the schema"},
		"not null twice":               {"-- godwit: add-not-null item.note\n", "is already NOT NULL"},
		"column already there":         {"-- godwit: add-column shop.tag text\n", "tag already exists"},
		"not null without a default":   {"-- godwit: add-column shop.zone text not-null\n", "no default= to fill"},
		"nothing to batch on":          {"-- godwit: add-column nokey.zone text default='x' not-null\n", "no single-column primary key to batch on"},
		"index already there":          {"-- godwit: add-index shop (tag) name=shop_tag_idx\n", "already exists; drop it first"},
		"index name taken by a table":  {"-- godwit: add-index shop (tag) name=item\n", "is not an index"},
		"missing index":                {"-- godwit: drop-index ghost_idx\n", "does not exist in the schema"},
		"dropping a table":             {"-- godwit: drop-index item\n", "is not an index (relkind r)"},
		"index backing a constraint":   {"-- godwit: drop-index item_note_uq\n", "backs the constraint item_note_uq"},
		"fk on a missing column":       {"-- godwit: add-fk item.ghost -> shop.id\n", "does not exist in the schema"},
		"fk to a missing table":        {"-- godwit: add-fk item.shop_id -> ghost.id\n", "does not exist in the schema"},
		"fk to a plain column":         {"-- godwit: add-fk item.shop_id -> shop.tag\n", "no single-column unique index"},
		"check name taken":             {"-- godwit: add-check item item_note_uq 'length(note) > 0'\n", "already has a constraint named"},
		"dropping a missing column":    {"-- godwit: drop-column shop.ghost\n", "does not exist in the schema"},
		"two indexes, one name":        {"-- godwit: add-index shop (tag) name=x\n-- godwit: add-index shop (price) name=x\n", "already the subject"},
		"two checks, one name":         {"-- godwit: add-check shop c 'price > 0'\n-- godwit: add-check shop c 'price < 9'\n", "already the subject"},
	} {
		t.Run(name, func(t *testing.T) {
			_, err := expandOne(t, conn, tc.up, "SELECT 1;\n")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
		})
	}
}

// TestExpandSimpleCatalogErrors walks every catalog probe of each operation, failing one per pass, so no
// probe reports a broken database as a successful expansion.
func TestExpandSimpleCatalogErrors(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL, itemDDL, `CREATE INDEX shop_tag_idx ON public.shop (tag)`)
	for _, up := range []string{
		"-- godwit: add-not-null shop.tag\n",
		"-- godwit: add-column shop.zone text default='x' not-null\n",
		"-- godwit: add-index shop (price)\n",
		"-- godwit: drop-index shop_tag_idx\n",
		"-- godwit: add-fk item.shop_id -> shop.id\n",
		"-- godwit: add-check shop shop_price_check 'price > 0'\n",
		"-- godwit: drop-column shop.price\n",
	} {
		total := 0
		if _, err := expandOne(t, flakyDB{DB: conn, n: &total, fail: 0}, up, "SELECT 1;\n"); err != nil {
			t.Fatalf("%s: %v", up, err)
		}
		for i := 1; i <= total; i++ {
			n := 0
			if _, err := expandOne(t, flakyDB{DB: conn, n: &n, fail: i}, up, "SELECT 1;\n"); err == nil {
				t.Fatalf("%s: probe %d must fail", up, i)
			}
		}
	}
}

func TestExpandSimpleHelpers(t *testing.T) {
	t.Parallel()
	conn := newScratch(t, shopDDL)
	if _, err := NewExpander().one(context.Background(), conn, engine.Directive{Op: engine.DirectiveRevert}); err == nil ||
		!strings.Contains(err.Error(), "has no expansion") {
		t.Fatalf("err = %v", err)
	}
	if got := indexColumns("("); got != nil {
		t.Fatalf("index columns = %v", got)
	}
	if got := indexColumns("(lower(tag), price)"); len(got) != 2 || got[0] != "expr" || got[1] != "price" {
		t.Fatalf("index columns = %v", got)
	}
	if got := subject(engine.Directive{Op: engine.DirectiveRevert}); got != engine.DirectiveRevert {
		t.Fatalf("subject = %q", got)
	}
	if got := keyAdvice("add-column"); got != "" {
		t.Fatalf("key advice = %q", got)
	}
}
